# Generated by Django 2.2.7 on 2019-12-02 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='application',
        ),
        migrations.DeleteModel(
            name='MedicineApplication',
        ),
    ]
