# Generated by Django 2.2.7 on 2019-12-02 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_auto_20191202_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='Illness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
            ],
        ),
        migrations.AddField(
            model_name='medicine',
            name='illness',
            field=models.ManyToManyField(blank=True, null=True, to='pharmacy.Illness', verbose_name='Doenças'),
        ),
    ]
