# Generated by Django 2.2.7 on 2019-12-05 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_auto_20191203_0838'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lot',
            options={'ordering': ['entry_date', 'shelf_life_date']},
        ),
    ]
