# Generated by Django 2.2.7 on 2019-12-02 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_auto_20191202_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='illness',
            field=models.ManyToManyField(blank=True, to='pharmacy.Illness', verbose_name='Doenças'),
        ),
    ]
