# Generated by Django 2.2.7 on 2020-03-04 11:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
        ('pharmacy', '0004_auto_20191211_0755'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='supplier',
            field=models.CharField(default='teste', max_length=200, verbose_name='Fornecedor'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='FreeSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime(2020, 3, 4, 8, 28, 24, 812293), verbose_name='Data')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.Medicine')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.Patient')),
            ],
        ),
    ]
