# Generated by Django 2.2.7 on 2020-03-05 16:53

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0005_auto_20200304_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freesample',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 3, 5, 16, 53, 21, 170461, tzinfo=utc), verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='freesample',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.Medicine', verbose_name='Medicamento'),
        ),
        migrations.AlterField(
            model_name='freesample',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.Patient', verbose_name='Paciente'),
        ),
    ]
