# Generated by Django 2.2.7 on 2020-03-05 17:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0006_auto_20200305_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freesample',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 3, 5, 17, 26, 37, 147477, tzinfo=utc), verbose_name='Data'),
        ),
    ]
