# Generated by Django 2.2.7 on 2020-03-13 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0006_auto_20200305_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freesample',
            name='date',
            field=models.DateField(verbose_name='Data'),
        ),
    ]
