# Generated by Django 2.2.7 on 2020-03-11 11:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0007_auto_20200305_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freesample',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 3, 11, 11, 6, 22, 908966, tzinfo=utc), verbose_name='Data'),
        ),
    ]
