# Generated by Django 2.2.7 on 2020-02-16 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spirometry', '0002_auto_20200216_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spirometry',
            name='date',
            field=models.DateField(verbose_name='Data'),
        ),
    ]
