# Generated by Django 2.2.7 on 2019-12-03 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(verbose_name='Hora de Início')),
                ('end', models.DateTimeField(verbose_name='Hora de Fim')),
                ('status', models.CharField(choices=[('scheduled', 'Agendado'), ('cancelled', 'Cancelado'), ('did-not-attend', 'Não Compareceu'), ('answered', 'Atendido')], default='scheduled', max_length=15)),
                ('notes', models.TextField(verbose_name='Descrição')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.Patient', verbose_name='Paciente')),
            ],
        ),
    ]
