# Generated by Django 2.2.7 on 2019-11-13 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Agendado'), ('cancelled', 'Cancelado'), ('did-not-attend', 'Não Compareceu'), ('answered', 'Atendido')], max_length=15),
        ),
    ]
