# Generated by Django 2.2.7 on 2019-11-20 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20191113_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Agendado'), ('cancelled', 'Cancelado'), ('did-not-attend', 'Não Compareceu'), ('answered', 'Atendido')], default='scheduled', max_length=15),
        ),
    ]
