# Generated by Django 2.2.7 on 2019-11-23 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20191119_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='notes',
            field=models.TextField(default='teste', verbose_name='Descrição'),
            preserve_default=False,
        ),
    ]
