# Generated by Django 2.2.7 on 2019-11-14 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='Nome de Usuário')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
