# Generated by Django 2.2.7 on 2019-11-27 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_auto_20191122_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='convenio',
            field=models.CharField(default='', max_length=50, verbose_name='Convênio'),
            preserve_default=False,
        ),
    ]
