# Generated by Django 2.2.7 on 2019-12-02 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('immunotherapy', '0002_illness'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Illness',
        ),
    ]
