# Generated by Django 2.2.7 on 2019-12-05 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('immunotherapy', '0002_auto_20191205_1127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='immunotherapy',
            old_name='end',
            new_name='start_date',
        ),
        migrations.RemoveField(
            model_name='immunotherapy',
            name='start',
        ),
    ]
