# Generated by Django 2.2.7 on 2019-12-11 10:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('immunotherapy', '0003_auto_20191205_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='immunotherapy',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data de Fim'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bottle',
            name='bottle_number',
            field=models.IntegerField(verbose_name='Numero'),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.Lot', verbose_name='Lote'),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='status',
            field=models.CharField(choices=[('in-use', 'Em uso'), ('used', 'usado')], default='in-use', max_length=15),
        ),
        migrations.AlterField(
            model_name='immunotherapy',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.Medicine', verbose_name='Remédio'),
        ),
        migrations.AlterField(
            model_name='immunotherapy',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.Patient', verbose_name='Paciente'),
        ),
        migrations.AlterField(
            model_name='immunotherapy',
            name='start_date',
            field=models.DateField(verbose_name='Data de Inicio'),
        ),
        migrations.AlterField(
            model_name='immunotherapy',
            name='status',
            field=models.CharField(choices=[('finished', 'Finalizado'), ('in-progress', 'Em Andamento')], default='in-progress', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='immunotherapy',
            name='total_applications',
            field=models.IntegerField(verbose_name='Total de aplicações'),
        ),
    ]
