# Generated by Django 2.2.7 on 2019-12-11 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immunotherapy', '0004_auto_20191211_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immunotherapy',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Fim'),
        ),
    ]
