# Generated by Django 2.2.7 on 2019-12-11 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('immunotherapy', '0005_auto_20191211_1008'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['date']},
        ),
        migrations.RemoveField(
            model_name='bottle',
            name='immunotherapy',
        ),
        migrations.RemoveField(
            model_name='bottle',
            name='status',
        ),
        migrations.AddField(
            model_name='immunotherapy',
            name='bottle',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='immunotherapy.Bottle'),
        ),
    ]
