# Generated by Django 2.2.7 on 2020-02-16 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('immunotherapy', '0006_auto_20191211_1107'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ('-date',)},
        ),
        migrations.AlterModelOptions(
            name='immunotherapy',
            options={'ordering': ('status', 'start_date')},
        ),
    ]
