# Generated by Django 2.2.7 on 2020-03-06 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('immunotherapy', '0007_auto_20200216_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='immunotherapy',
            name='illness',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy.Illness', verbose_name='Doença'),
        ),
    ]
