# Generated by Django 2.2.7 on 2020-06-02 11:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('immunotherapy', '0008_immunotherapy_illness'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bottle',
            options={'ordering': ['start_date', 'end_date']},
        ),
        migrations.RenameField(
            model_name='bottle',
            old_name='bottle_number',
            new_name='number',
        ),
        migrations.RemoveField(
            model_name='bottle',
            name='lot',
        ),
        migrations.RemoveField(
            model_name='immunotherapy',
            name='bottle',
        ),
        migrations.RemoveField(
            model_name='immunotherapy',
            name='total_applications',
        ),
        migrations.AddField(
            model_name='bottle',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Fim'),
        ),
        migrations.AddField(
            model_name='bottle',
            name='immunotherapy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='immunotherapy.Immunotherapy'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bottle',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data de inicio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='immunotherapy',
            name='total_bottles',
            field=models.IntegerField(verbose_name='Total de Frascos'),
            preserve_default=False,
        ),
    ]
