# Generated by Django 2.2.7 on 2020-06-02 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immunotherapy', '0009_auto_20200602_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='dosage',
            field=models.CharField(max_length=10, verbose_name='Dosagem'),
        ),
    ]
