# Generated by Django 2.2.7 on 2020-06-10 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immunotherapy', '0010_auto_20200602_0920'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='immunotherapy',
            options={'ordering': ('-status', 'start_date')},
        ),
        migrations.AddField(
            model_name='immunotherapy',
            name='total_applications',
            field=models.IntegerField(verbose_name='Total de Aplicações'),
            preserve_default=False,
        ),
    ]
