# Generated by Django 2.2.7 on 2020-06-11 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('immunotherapy', '0011_auto_20200610_2051'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ('application_number',)},
        ),
        migrations.RemoveField(
            model_name='application',
            name='bottle',
        ),
        migrations.AddField(
            model_name='application',
            name='application_number',
            field=models.IntegerField(verbose_name='Applicação'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='bottle_number',
            field=models.IntegerField(verbose_name='Frasco'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='immunotherapy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='immunotherapy.Immunotherapy'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Bottle',
        ),
    ]
