# Generated by Django 2.2.7 on 2020-07-03 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immunotherapy', '0012_auto_20200610_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='application_number',
            field=models.IntegerField(verbose_name='Dose'),
        ),
    ]
